SELECT ORDER_ID, ORDER_ITEM_ID,
    PRODUCT_ID,
    SELLER_ID,
    SHIPPING_LIMIT_DATE::DATE AS SHIPPING_DATE, 
    ROUND(PRICE, 2) AS PRICE,                   
    ROUND(FREIGHT_VALUE, 2) AS FREIGHT_VALUE    
FROM {{   ref("STG_Orders_Items")   }}